- name: Revisar estado de Laravel
  shell: powershell
  run: |
    cd C:\laragon\www\mar
    echo "OS: $env:RUNNER_OS"
    echo "NAME: $env:RUNNER_NAME"
    if (Test-Path "storage\framework\down") {
        echo "ESTADO: DOWN"
    } else {
        echo "ESTADO: UP"
    }
